//
// File generated by rootcint at Thu Oct 19 14:20:14 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME RootClasses_dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "RootClasses_dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void B4ROOTHit_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_B4ROOTHit(void *p = 0);
   static void *newArray_B4ROOTHit(Long_t size, void *p);
   static void delete_B4ROOTHit(void *p);
   static void deleteArray_B4ROOTHit(void *p);
   static void destruct_B4ROOTHit(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::B4ROOTHit*)
   {
      ::B4ROOTHit *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::B4ROOTHit >(0);
      static ::ROOT::TGenericClassInfo 
         instance("B4ROOTHit", ::B4ROOTHit::Class_Version(), "./include/B4ROOTEvent.hh", 19,
                  typeid(::B4ROOTHit), DefineBehavior(ptr, ptr),
                  &::B4ROOTHit::Dictionary, isa_proxy, 4,
                  sizeof(::B4ROOTHit) );
      instance.SetNew(&new_B4ROOTHit);
      instance.SetNewArray(&newArray_B4ROOTHit);
      instance.SetDelete(&delete_B4ROOTHit);
      instance.SetDeleteArray(&deleteArray_B4ROOTHit);
      instance.SetDestructor(&destruct_B4ROOTHit);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::B4ROOTHit*)
   {
      return GenerateInitInstanceLocal((::B4ROOTHit*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::B4ROOTHit*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

namespace ROOT {
   void B4ROOTEvent_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_B4ROOTEvent(void *p = 0);
   static void *newArray_B4ROOTEvent(Long_t size, void *p);
   static void delete_B4ROOTEvent(void *p);
   static void deleteArray_B4ROOTEvent(void *p);
   static void destruct_B4ROOTEvent(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::B4ROOTEvent*)
   {
      ::B4ROOTEvent *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::B4ROOTEvent >(0);
      static ::ROOT::TGenericClassInfo 
         instance("B4ROOTEvent", ::B4ROOTEvent::Class_Version(), "./include/B4ROOTEvent.hh", 94,
                  typeid(::B4ROOTEvent), DefineBehavior(ptr, ptr),
                  &::B4ROOTEvent::Dictionary, isa_proxy, 4,
                  sizeof(::B4ROOTEvent) );
      instance.SetNew(&new_B4ROOTEvent);
      instance.SetNewArray(&newArray_B4ROOTEvent);
      instance.SetDelete(&delete_B4ROOTEvent);
      instance.SetDeleteArray(&deleteArray_B4ROOTEvent);
      instance.SetDestructor(&destruct_B4ROOTEvent);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::B4ROOTEvent*)
   {
      return GenerateInitInstanceLocal((::B4ROOTEvent*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::B4ROOTEvent*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
atomic_TClass_ptr B4ROOTHit::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *B4ROOTHit::Class_Name()
{
   return "B4ROOTHit";
}

//______________________________________________________________________________
const char *B4ROOTHit::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::B4ROOTHit*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int B4ROOTHit::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::B4ROOTHit*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void B4ROOTHit::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::B4ROOTHit*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *B4ROOTHit::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::B4ROOTHit*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
atomic_TClass_ptr B4ROOTEvent::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *B4ROOTEvent::Class_Name()
{
   return "B4ROOTEvent";
}

//______________________________________________________________________________
const char *B4ROOTEvent::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::B4ROOTEvent*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int B4ROOTEvent::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::B4ROOTEvent*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void B4ROOTEvent::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::B4ROOTEvent*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *B4ROOTEvent::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::B4ROOTEvent*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void B4ROOTEvent::Streamer(TBuffer &R__b)
{
   // Stream an object of class B4ROOTEvent.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(B4ROOTEvent::Class(),this);
   } else {
      R__b.WriteClassBuffer(B4ROOTEvent::Class(),this);
   }
}

//______________________________________________________________________________
void B4ROOTEvent::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class B4ROOTEvent.
      TClass *R__cl = ::B4ROOTEvent::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_EventNo", &m_EventNo);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_GapEnergy", &m_GapEnergy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_NHits", &m_NHits);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_AbsoThickness", &m_AbsoThickness);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_GapThickness", &m_GapThickness);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_Layerno", &m_Layerno);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_tilesizeX", &m_tilesizeX);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_tilesizeY", &m_tilesizeY);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_calsizeXY", &m_calsizeXY);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "absofirst", &absofirst);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_MomentumPh1", &m_MomentumPh1);
      R__insp.InspectMember(m_MomentumPh1, "m_MomentumPh1.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_GunPos", &m_GunPos);
      R__insp.InspectMember(m_GunPos, "m_GunPos.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_Hits", &m_Hits);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_B4ROOTEvent(void *p) {
      return  p ? new(p) ::B4ROOTEvent : new ::B4ROOTEvent;
   }
   static void *newArray_B4ROOTEvent(Long_t nElements, void *p) {
      return p ? new(p) ::B4ROOTEvent[nElements] : new ::B4ROOTEvent[nElements];
   }
   // Wrapper around operator delete
   static void delete_B4ROOTEvent(void *p) {
      delete ((::B4ROOTEvent*)p);
   }
   static void deleteArray_B4ROOTEvent(void *p) {
      delete [] ((::B4ROOTEvent*)p);
   }
   static void destruct_B4ROOTEvent(void *p) {
      typedef ::B4ROOTEvent current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::B4ROOTEvent

//______________________________________________________________________________
void B4ROOTHit::Streamer(TBuffer &R__b)
{
   // Stream an object of class B4ROOTHit.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(B4ROOTHit::Class(),this);
   } else {
      R__b.WriteClassBuffer(B4ROOTHit::Class(),this);
   }
}

//______________________________________________________________________________
void B4ROOTHit::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class B4ROOTHit.
      TClass *R__cl = ::B4ROOTHit::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_X", &m_X);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_Y", &m_Y);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_Z", &m_Z);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_EnergyDeposit", &m_EnergyDeposit);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_B4ROOTHit(void *p) {
      return  p ? new(p) ::B4ROOTHit : new ::B4ROOTHit;
   }
   static void *newArray_B4ROOTHit(Long_t nElements, void *p) {
      return p ? new(p) ::B4ROOTHit[nElements] : new ::B4ROOTHit[nElements];
   }
   // Wrapper around operator delete
   static void delete_B4ROOTHit(void *p) {
      delete ((::B4ROOTHit*)p);
   }
   static void deleteArray_B4ROOTHit(void *p) {
      delete [] ((::B4ROOTHit*)p);
   }
   static void destruct_B4ROOTHit(void *p) {
      typedef ::B4ROOTHit current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::B4ROOTHit

/********************************************************
* RootClasses_dict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableRootClasses_dict();

extern "C" void G__set_cpp_environmentRootClasses_dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("include/B4ROOTEvent.hh");
  G__cpp_reset_tagtableRootClasses_dict();
}
#include <new>
extern "C" int G__cpp_dllrevRootClasses_dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* B4ROOTHit */
static int G__RootClasses_dict_266_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   B4ROOTHit* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new B4ROOTHit[n];
     } else {
       p = new((void*) gvp) B4ROOTHit[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new B4ROOTHit;
     } else {
       p = new((void*) gvp) B4ROOTHit;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__RootClasses_dictLN_B4ROOTHit));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_266_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   B4ROOTHit* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new B4ROOTHit(*(B4ROOTHit*) libp->para[0].ref);
   } else {
     p = new((void*) gvp) B4ROOTHit(*(B4ROOTHit*) libp->para[0].ref);
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__RootClasses_dictLN_B4ROOTHit));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_266_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const B4ROOTHit*) G__getstructoffset())->X());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_266_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const B4ROOTHit*) G__getstructoffset())->Y());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_266_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const B4ROOTHit*) G__getstructoffset())->Z());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_266_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const B4ROOTHit*) G__getstructoffset())->EnergyDeposit());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_266_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((B4ROOTHit*) G__getstructoffset())->SetCoordinates((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_266_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((B4ROOTHit*) G__getstructoffset())->SetEnergyDeposit((Double_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_266_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) B4ROOTHit::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_266_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) B4ROOTHit::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_266_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) B4ROOTHit::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_266_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      B4ROOTHit::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_266_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((B4ROOTHit*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_266_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) B4ROOTHit::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_266_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) B4ROOTHit::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_266_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) B4ROOTHit::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_266_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) B4ROOTHit::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef B4ROOTHit G__TB4ROOTHit;
static int G__RootClasses_dict_266_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (B4ROOTHit*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((B4ROOTHit*) (soff+(sizeof(B4ROOTHit)*i)))->~G__TB4ROOTHit();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (B4ROOTHit*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((B4ROOTHit*) (soff))->~G__TB4ROOTHit();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__RootClasses_dict_266_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   B4ROOTHit* dest = (B4ROOTHit*) G__getstructoffset();
   *dest = *(B4ROOTHit*) libp->para[0].ref;
   const B4ROOTHit& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* B4ROOTEvent */
static int G__RootClasses_dict_267_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   B4ROOTEvent* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new B4ROOTEvent[n];
     } else {
       p = new((void*) gvp) B4ROOTEvent[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new B4ROOTEvent;
     } else {
       p = new((void*) gvp) B4ROOTEvent;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__RootClasses_dictLN_B4ROOTEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_267_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   B4ROOTEvent* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new B4ROOTEvent(*(B4ROOTEvent*) libp->para[0].ref);
   } else {
     p = new((void*) gvp) B4ROOTEvent(*(B4ROOTEvent*) libp->para[0].ref);
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__RootClasses_dictLN_B4ROOTEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_267_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      B4ROOTEvent::Reset((Option_t*) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      B4ROOTEvent::Reset();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_267_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const B4ROOTEvent*) G__getstructoffset())->EventNo());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_267_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const B4ROOTEvent*) G__getstructoffset())->GapEnergy());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_267_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((B4ROOTEvent*) G__getstructoffset())->AbsoThickness());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_267_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((B4ROOTEvent*) G__getstructoffset())->GapThickness());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_267_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((B4ROOTEvent*) G__getstructoffset())->NumberOfLayers());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_267_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((B4ROOTEvent*) G__getstructoffset())->TilesizeX());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_267_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((B4ROOTEvent*) G__getstructoffset())->TilesizeY());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_267_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((B4ROOTEvent*) G__getstructoffset())->calsizeXY());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_267_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((B4ROOTEvent*) G__getstructoffset())->GetAbsFirst());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_267_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TVector3* pobj;
         TVector3 xobj = ((B4ROOTEvent*) G__getstructoffset())->MomentumPh1();
         pobj = new TVector3(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_267_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TVector3* pobj;
         TVector3 xobj = ((B4ROOTEvent*) G__getstructoffset())->GunPos();
         pobj = new TVector3(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_267_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const B4ROOTEvent*) G__getstructoffset())->NHits());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_267_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const B4ROOTEvent*) G__getstructoffset())->Hits());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_267_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((B4ROOTEvent*) G__getstructoffset())->Hit((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_267_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((B4ROOTEvent*) G__getstructoffset())->SetEventNo((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_267_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((B4ROOTEvent*) G__getstructoffset())->SetGapEnergy((Double_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_267_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((B4ROOTEvent*) G__getstructoffset())->SetAbsoThickness((Double_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_267_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((B4ROOTEvent*) G__getstructoffset())->SetGapThickness((Double_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_267_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((B4ROOTEvent*) G__getstructoffset())->SetNumberOfLayers((Double_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_267_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((B4ROOTEvent*) G__getstructoffset())->SetTilesizeX((Double_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_267_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((B4ROOTEvent*) G__getstructoffset())->SetTilesizeY((Double_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_267_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((B4ROOTEvent*) G__getstructoffset())->SetcalsizeXY((Double_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_267_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((B4ROOTEvent*) G__getstructoffset())->SetAbsFirst((Bool_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_267_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((B4ROOTEvent*) G__getstructoffset())->SetMomentumPh1((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_267_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((B4ROOTEvent*) G__getstructoffset())->SetGunPos(*((TVector3*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_267_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((B4ROOTEvent*) G__getstructoffset())->AddHit(*(B4ROOTHit*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_267_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) B4ROOTEvent::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_267_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) B4ROOTEvent::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_267_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) B4ROOTEvent::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_267_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      B4ROOTEvent::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_267_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((B4ROOTEvent*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_267_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) B4ROOTEvent::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_267_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) B4ROOTEvent::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_267_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) B4ROOTEvent::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RootClasses_dict_267_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) B4ROOTEvent::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef B4ROOTEvent G__TB4ROOTEvent;
static int G__RootClasses_dict_267_0_43(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (B4ROOTEvent*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((B4ROOTEvent*) (soff+(sizeof(B4ROOTEvent)*i)))->~G__TB4ROOTEvent();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (B4ROOTEvent*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((B4ROOTEvent*) (soff))->~G__TB4ROOTEvent();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__RootClasses_dict_267_0_44(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   B4ROOTEvent* dest = (B4ROOTEvent*) G__getstructoffset();
   *dest = *(B4ROOTEvent*) libp->para[0].ref;
   const B4ROOTEvent& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* B4ROOTHit */

/* B4ROOTEvent */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncRootClasses_dict {
 public:
  G__Sizep2memfuncRootClasses_dict(): p(&G__Sizep2memfuncRootClasses_dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncRootClasses_dict::*p)();
};

size_t G__get_sizep2memfuncRootClasses_dict()
{
  G__Sizep2memfuncRootClasses_dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceRootClasses_dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__RootClasses_dictLN_B4ROOTHit))) {
     B4ROOTHit *G__Lderived;
     G__Lderived=(B4ROOTHit*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__RootClasses_dictLN_B4ROOTHit),G__get_linked_tagnum(&G__RootClasses_dictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__RootClasses_dictLN_B4ROOTEvent))) {
     B4ROOTEvent *G__Lderived;
     G__Lderived=(B4ROOTEvent*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__RootClasses_dictLN_B4ROOTEvent),G__get_linked_tagnum(&G__RootClasses_dictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableRootClasses_dict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("Option_t",99,-1,256,-1);
   G__setnewtype(-1,"Option string (const char)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__RootClasses_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__RootClasses_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__RootClasses_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__RootClasses_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__RootClasses_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__RootClasses_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__RootClasses_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__RootClasses_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__RootClasses_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__RootClasses_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__RootClasses_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__RootClasses_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__RootClasses_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__RootClasses_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__RootClasses_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__RootClasses_dictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__RootClasses_dictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__RootClasses_dictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__RootClasses_dictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__RootClasses_dictLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__RootClasses_dictLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__RootClasses_dictLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__RootClasses_dictLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__RootClasses_dictLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__RootClasses_dictLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__RootClasses_dictLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__RootClasses_dictLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__RootClasses_dictLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__RootClasses_dictLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__RootClasses_dictLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__RootClasses_dictLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__RootClasses_dictLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__RootClasses_dictLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__RootClasses_dictLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__RootClasses_dictLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__RootClasses_dictLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* B4ROOTHit */
static void G__setup_memvarB4ROOTHit(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__RootClasses_dictLN_B4ROOTHit));
   { B4ROOTHit *p; p=(B4ROOTHit*)0x1000; if (p) { }
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"m_X=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"m_Y=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"m_Z=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"m_EnergyDeposit=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__RootClasses_dictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* B4ROOTEvent */
static void G__setup_memvarB4ROOTEvent(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__RootClasses_dictLN_B4ROOTEvent));
   { B4ROOTEvent *p; p=(B4ROOTEvent*)0x1000; if (p) { }
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"m_EventNo=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"m_GapEnergy=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"m_NHits=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"m_AbsoThickness=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"m_GapThickness=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"m_Layerno=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"m_tilesizeX=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"m_tilesizeY=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"m_calsizeXY=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"absofirst=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__RootClasses_dictLN_TVector3),-1,-1,4,"m_MomentumPh1=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__RootClasses_dictLN_TVector3),-1,-1,4,"m_GunPos=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__RootClasses_dictLN_TClonesArray),-1,-1,4,"m_Hits=",0,"->");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__RootClasses_dictLN_TClonesArray),-1,-2,4,"aHits=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__RootClasses_dictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarRootClasses_dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncB4ROOTHit(void) {
   /* B4ROOTHit */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__RootClasses_dictLN_B4ROOTHit));
   G__memfunc_setup("B4ROOTHit",735,G__RootClasses_dict_266_0_1, 105, G__get_linked_tagnum(&G__RootClasses_dictLN_B4ROOTHit), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("B4ROOTHit",735,G__RootClasses_dict_266_0_2, 105, G__get_linked_tagnum(&G__RootClasses_dictLN_B4ROOTHit), -1, 0, 1, 1, 1, 0, "u 'B4ROOTHit' - 11 - orig", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Clear",487,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - 'Option_t' 10 '\"\"' option", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("X",88,G__RootClasses_dict_266_0_4, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Y",89,G__RootClasses_dict_266_0_5, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Z",90,G__RootClasses_dict_266_0_6, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("EnergyDeposit",1346,G__RootClasses_dict_266_0_7, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetCoordinates",1447,G__RootClasses_dict_266_0_8, 121, -1, -1, 0, 3, 1, 1, 0, 
"d - 'Double_t' 0 - x d - 'Double_t' 0 - y "
"d - 'Double_t' 0 - z", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetEnergyDeposit",1646,G__RootClasses_dict_266_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "d - 'Double_t' 0 - dep", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__RootClasses_dict_266_0_10, 85, G__get_linked_tagnum(&G__RootClasses_dictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&B4ROOTHit::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__RootClasses_dict_266_0_11, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&B4ROOTHit::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__RootClasses_dict_266_0_12, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&B4ROOTHit::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__RootClasses_dict_266_0_13, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&B4ROOTHit::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__RootClasses_dictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__RootClasses_dict_266_0_17, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__RootClasses_dict_266_0_18, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&B4ROOTHit::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__RootClasses_dict_266_0_19, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&B4ROOTHit::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__RootClasses_dict_266_0_20, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&B4ROOTHit::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__RootClasses_dict_266_0_21, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&B4ROOTHit::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~B4ROOTHit", 861, G__RootClasses_dict_266_0_22, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__RootClasses_dict_266_0_23, (int) ('u'), G__get_linked_tagnum(&G__RootClasses_dictLN_B4ROOTHit), -1, 1, 1, 1, 1, 0, "u 'B4ROOTHit' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncB4ROOTEvent(void) {
   /* B4ROOTEvent */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__RootClasses_dictLN_B4ROOTEvent));
   G__memfunc_setup("B4ROOTEvent",956,G__RootClasses_dict_267_0_1, 105, G__get_linked_tagnum(&G__RootClasses_dictLN_B4ROOTEvent), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("B4ROOTEvent",956,G__RootClasses_dict_267_0_2, 105, G__get_linked_tagnum(&G__RootClasses_dictLN_B4ROOTEvent), -1, 0, 1, 1, 1, 0, "u 'B4ROOTEvent' - 11 - origEvent", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Clear",487,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - 'Option_t' 10 '\"\"' option", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Reset",515,G__RootClasses_dict_267_0_4, 121, -1, -1, 0, 1, 3, 1, 0, "C - 'Option_t' 10 '\"\"' option", (char*)NULL, (void*) G__func2void( (void (*)(Option_t*))(&B4ROOTEvent::Reset) ), 0);
   G__memfunc_setup("EventNo",703,G__RootClasses_dict_267_0_5, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GapEnergy",898,G__RootClasses_dict_267_0_6, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AbsoThickness",1329,G__RootClasses_dict_267_0_7, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GapThickness",1220,G__RootClasses_dict_267_0_8, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NumberOfLayers",1422,G__RootClasses_dict_267_0_9, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TilesizeX",929,G__RootClasses_dict_267_0_10, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TilesizeY",930,G__RootClasses_dict_267_0_11, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("calsizeXY",924,G__RootClasses_dict_267_0_12, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetAbsFirst",1086,G__RootClasses_dict_267_0_13, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MomentumPh1",1083,G__RootClasses_dict_267_0_14, 117, G__get_linked_tagnum(&G__RootClasses_dictLN_TVector3), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GunPos",604,G__RootClasses_dict_267_0_15, 117, G__get_linked_tagnum(&G__RootClasses_dictLN_TVector3), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NHits",486,G__RootClasses_dict_267_0_16, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Hits",408,G__RootClasses_dict_267_0_17, 85, G__get_linked_tagnum(&G__RootClasses_dictLN_TClonesArray), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Hit",293,G__RootClasses_dict_267_0_18, 85, G__get_linked_tagnum(&G__RootClasses_dictLN_B4ROOTHit), -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetEventNo",1003,G__RootClasses_dict_267_0_19, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - evN", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetGapEnergy",1198,G__RootClasses_dict_267_0_20, 121, -1, -1, 0, 1, 1, 1, 0, "d - 'Double_t' 0 - en", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetAbsoThickness",1629,G__RootClasses_dict_267_0_21, 121, -1, -1, 0, 1, 1, 1, 0, "d - 'Double_t' 0 - at", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetGapThickness",1520,G__RootClasses_dict_267_0_22, 121, -1, -1, 0, 1, 1, 1, 0, "d - 'Double_t' 0 - gt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetNumberOfLayers",1722,G__RootClasses_dict_267_0_23, 121, -1, -1, 0, 1, 1, 1, 0, "d - 'Double_t' 0 - nol", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTilesizeX",1229,G__RootClasses_dict_267_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "d - 'Double_t' 0 - tsX", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTilesizeY",1230,G__RootClasses_dict_267_0_25, 121, -1, -1, 0, 1, 1, 1, 0, "d - 'Double_t' 0 - tsY", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetcalsizeXY",1224,G__RootClasses_dict_267_0_26, 121, -1, -1, 0, 1, 1, 1, 0, "d - 'Double_t' 0 - cxy", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetAbsFirst",1098,G__RootClasses_dict_267_0_27, 121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 - cfg", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetMomentumPh1",1383,G__RootClasses_dict_267_0_28, 121, -1, -1, 0, 3, 1, 1, 0, 
"d - 'Double_t' 0 - mx1 d - 'Double_t' 0 - my1 "
"d - 'Double_t' 0 - mz1", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetGunPos",904,G__RootClasses_dict_267_0_29, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TVector3' - 0 - gp", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddHit",558,G__RootClasses_dict_267_0_30, 85, G__get_linked_tagnum(&G__RootClasses_dictLN_B4ROOTHit), -1, 0, 1, 1, 1, 0, "u 'B4ROOTHit' - 1 - cand", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__RootClasses_dict_267_0_31, 85, G__get_linked_tagnum(&G__RootClasses_dictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&B4ROOTEvent::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__RootClasses_dict_267_0_32, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&B4ROOTEvent::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__RootClasses_dict_267_0_33, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&B4ROOTEvent::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__RootClasses_dict_267_0_34, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&B4ROOTEvent::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__RootClasses_dictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__RootClasses_dict_267_0_38, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__RootClasses_dict_267_0_39, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&B4ROOTEvent::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__RootClasses_dict_267_0_40, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&B4ROOTEvent::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__RootClasses_dict_267_0_41, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&B4ROOTEvent::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__RootClasses_dict_267_0_42, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&B4ROOTEvent::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~B4ROOTEvent", 1082, G__RootClasses_dict_267_0_43, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__RootClasses_dict_267_0_44, (int) ('u'), G__get_linked_tagnum(&G__RootClasses_dictLN_B4ROOTEvent), -1, 1, 1, 1, 1, 0, "u 'B4ROOTEvent' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncRootClasses_dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalRootClasses_dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcRootClasses_dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__RootClasses_dictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__RootClasses_dictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__RootClasses_dictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__RootClasses_dictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__RootClasses_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__RootClasses_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__RootClasses_dictLN_TClonesArray = { "TClonesArray" , 99 , -1 };
G__linked_taginfo G__RootClasses_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__RootClasses_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__RootClasses_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__RootClasses_dictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__RootClasses_dictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__RootClasses_dictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__RootClasses_dictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__RootClasses_dictLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__RootClasses_dictLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__RootClasses_dictLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__RootClasses_dictLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__RootClasses_dictLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__RootClasses_dictLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__RootClasses_dictLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__RootClasses_dictLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__RootClasses_dictLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__RootClasses_dictLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__RootClasses_dictLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__RootClasses_dictLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__RootClasses_dictLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__RootClasses_dictLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__RootClasses_dictLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__RootClasses_dictLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__RootClasses_dictLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__RootClasses_dictLN_TVector3 = { "TVector3" , 99 , -1 };
G__linked_taginfo G__RootClasses_dictLN_B4ROOTHit = { "B4ROOTHit" , 99 , -1 };
G__linked_taginfo G__RootClasses_dictLN_B4ROOTEvent = { "B4ROOTEvent" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableRootClasses_dict() {
  G__RootClasses_dictLN_TClass.tagnum = -1 ;
  G__RootClasses_dictLN_TBuffer.tagnum = -1 ;
  G__RootClasses_dictLN_TMemberInspector.tagnum = -1 ;
  G__RootClasses_dictLN_TObject.tagnum = -1 ;
  G__RootClasses_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__RootClasses_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__RootClasses_dictLN_TClonesArray.tagnum = -1 ;
  G__RootClasses_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__RootClasses_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__RootClasses_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__RootClasses_dictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__RootClasses_dictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__RootClasses_dictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__RootClasses_dictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__RootClasses_dictLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__RootClasses_dictLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__RootClasses_dictLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__RootClasses_dictLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__RootClasses_dictLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__RootClasses_dictLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__RootClasses_dictLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__RootClasses_dictLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__RootClasses_dictLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__RootClasses_dictLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__RootClasses_dictLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__RootClasses_dictLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__RootClasses_dictLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__RootClasses_dictLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__RootClasses_dictLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__RootClasses_dictLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__RootClasses_dictLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__RootClasses_dictLN_TVector3.tagnum = -1 ;
  G__RootClasses_dictLN_B4ROOTHit.tagnum = -1 ;
  G__RootClasses_dictLN_B4ROOTEvent.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableRootClasses_dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__RootClasses_dictLN_TClass);
   G__get_linked_tagnum_fwd(&G__RootClasses_dictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__RootClasses_dictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__RootClasses_dictLN_TObject);
   G__get_linked_tagnum_fwd(&G__RootClasses_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__RootClasses_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__RootClasses_dictLN_TClonesArray);
   G__get_linked_tagnum_fwd(&G__RootClasses_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__RootClasses_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__RootClasses_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__RootClasses_dictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__RootClasses_dictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__RootClasses_dictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__RootClasses_dictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__RootClasses_dictLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__RootClasses_dictLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__RootClasses_dictLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__RootClasses_dictLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__RootClasses_dictLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__RootClasses_dictLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__RootClasses_dictLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__RootClasses_dictLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__RootClasses_dictLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__RootClasses_dictLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__RootClasses_dictLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__RootClasses_dictLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__RootClasses_dictLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__RootClasses_dictLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__RootClasses_dictLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__RootClasses_dictLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__RootClasses_dictLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__RootClasses_dictLN_TVector3);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__RootClasses_dictLN_B4ROOTHit),sizeof(B4ROOTHit),-1,292608,(char*)NULL,G__setup_memvarB4ROOTHit,G__setup_memfuncB4ROOTHit);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__RootClasses_dictLN_B4ROOTEvent),sizeof(B4ROOTEvent),-1,292608,(char*)NULL,G__setup_memvarB4ROOTEvent,G__setup_memfuncB4ROOTEvent);
}
extern "C" void G__cpp_setupRootClasses_dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupRootClasses_dict()");
  G__set_cpp_environmentRootClasses_dict();
  G__cpp_setup_tagtableRootClasses_dict();

  G__cpp_setup_inheritanceRootClasses_dict();

  G__cpp_setup_typetableRootClasses_dict();

  G__cpp_setup_memvarRootClasses_dict();

  G__cpp_setup_memfuncRootClasses_dict();
  G__cpp_setup_globalRootClasses_dict();
  G__cpp_setup_funcRootClasses_dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncRootClasses_dict();
  return;
}
class G__cpp_setup_initRootClasses_dict {
  public:
    G__cpp_setup_initRootClasses_dict() { G__add_setup_func("RootClasses_dict",(G__incsetup)(&G__cpp_setupRootClasses_dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initRootClasses_dict() { G__remove_setup_func("RootClasses_dict"); }
};
G__cpp_setup_initRootClasses_dict G__cpp_setup_initializerRootClasses_dict;

