/********************************************************************
* RootClasses_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error RootClasses_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableRootClasses_dict();
extern void G__cpp_setup_inheritanceRootClasses_dict();
extern void G__cpp_setup_typetableRootClasses_dict();
extern void G__cpp_setup_memvarRootClasses_dict();
extern void G__cpp_setup_globalRootClasses_dict();
extern void G__cpp_setup_memfuncRootClasses_dict();
extern void G__cpp_setup_funcRootClasses_dict();
extern void G__set_cpp_environmentRootClasses_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/B4ROOTEvent.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__RootClasses_dictLN_TClass;
extern G__linked_taginfo G__RootClasses_dictLN_TBuffer;
extern G__linked_taginfo G__RootClasses_dictLN_TMemberInspector;
extern G__linked_taginfo G__RootClasses_dictLN_TObject;
extern G__linked_taginfo G__RootClasses_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__RootClasses_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RootClasses_dictLN_TClonesArray;
extern G__linked_taginfo G__RootClasses_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__RootClasses_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RootClasses_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__RootClasses_dictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__RootClasses_dictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__RootClasses_dictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__RootClasses_dictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__RootClasses_dictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__RootClasses_dictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__RootClasses_dictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__RootClasses_dictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__RootClasses_dictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__RootClasses_dictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__RootClasses_dictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__RootClasses_dictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__RootClasses_dictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__RootClasses_dictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__RootClasses_dictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__RootClasses_dictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__RootClasses_dictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__RootClasses_dictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__RootClasses_dictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__RootClasses_dictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__RootClasses_dictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__RootClasses_dictLN_TVector3;
extern G__linked_taginfo G__RootClasses_dictLN_B4ROOTHit;
extern G__linked_taginfo G__RootClasses_dictLN_B4ROOTEvent;

/* STUB derived class for protected member access */
